### ISSUE TITLE
Foldername with Blank an square bracket

### ISSUE THREAD

**Issue by jpaechnatz** [quentinsf/IMAPdedup#13]
Howto use a Foldername like [Gmail]/Alle Nachrichten ?
I tried escaping the brackets with \ but it's not working, even entering the whole Folderpath in single quotes does not work.

**Comment by quentinsf** [comment]
Just (finally!) looking at this, and it works for me.  I put the whole foldername in quotes and it works ok.  I wonder if I took so long to get to it that Google fixed it at their end? :-)

If you're still interested, and want to try it, and still get an error, then give me a bit more detail and I'll take a look. 

All the best, 
Quentin

**Comment by tayyabsaeed** [comment]
Dear Sir,
We migrate lotus to zimbra, in migration we migrate some mailboxes 2 3 times because of network failure our large accounts stuck in between and then we re-run migration wizard due to this we found duplicate emails in our zimbra mailboxes, We are using imapdedup but it fails to remove emails from those folders which contain spaces in their name, kindly give any solution if you have, we are very thankful to u.

**Comment by tayyabsaeed** [comment]
here is error for above comment:
Error: Got response: ['SELECT failed'] from server
Error: Got response: ['SELECT failed'] from server
Error: Got response: ['SELECT failed'] from server
Traceback (most recent call last):
  File "imapdedup.py", line 310, in <module>
    main(sys.argv[1:])
  File "imapdedup.py", line 307, in main
    process(options, mboxes)
  File "imapdedup.py", line 215, in process
    msgs = check_response(server.select(mbox, options.dry_run))[0]
  File "/usr/lib64/python2.7/imaplib.py", line 661, in select
    typ, dat = self._simple_command(name, mailbox)
  File "/usr/lib64/python2.7/imaplib.py", line 1082, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib64/python2.7/imaplib.py", line 917, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: SELECT command error: BAD ['parse error: zero-length content']

**Comment by quentinsf** [comment]
Hello - 

You are not the first person to have this problem, but I think it should work if you put the mailbox name in quotes?  If that doesn't work you might even need double quotes, e.g.

   'My Mailbox'

or even

  '"My Mailbox"'

Does that work?

Another possibility might be to rename the folder, run the imapdedup command, then put the spaces back again?

All the best, 
Quentin

**Comment by tayyabsaeed** [comment]
Dear Sir, 

Thanks a lot, i will update you the result. 

Thank you so much again to reply me and let me know if you have or know about any paid solution for remove duplicate emails. 

Thanks, 
Tayyab Saeed 
----- Original Message -----
