### ISSUE TITLE
'utf7' codec can't decode byte

### ISSUE THREAD

**Issue by nerijus** [quentinsf/IMAPdedup#16]
Hi,
running ./imapdedup.py -s localhost -u user -l gives:

Traceback (most recent call last):
  File "./imapdedup.py", line 271, in <module>
    main()
  File "./imapdedup.py", line 164, in main
    mb = mb.decode('utf-7')
  File "/usr/lib64/python2.6/encodings/utf_7.py", line 12, in decode
    return codecs.utf_7_decode(input, errors, True)
UnicodeDecodeError: 'utf7' codec can't decode byte 0x5c in position 1: unexpected special character

**Comment by stronciy** [comment]
Hi, 

Did you find solution ?

**Comment by nerijus** [comment]
No.

**Comment by stronciy** [comment]
Ok, 
Pay attention that's happen just on CentOS 6.7 with python 2.6

On Debian Wheezy all work fine.

**Comment by nerijus** [comment]
Which python version on Debian? Tried with python 2.7 from The Software Collections  ( SCL ) repository for CentOS 6.x - the same.

**Comment by stronciy** [comment]
Exactly, so for correct work need to have python not less than 2.7

**Comment by fl0pp** [comment]
This projects seems quite dead, but I came across it some days ago. It worked on multiple email accounts in Office 365 / Exchange Online, but I experienced the same issue.

When i execute

```
./imapdedup.py -s imap-mail.outlook.com -u <user> -x -n -v -l
```

some folders are listed OK, but then I get the following exception:

```
Traceback (most recent call last):
  File "./imapdedup.py", line 326, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 323, in main
    process(options, mboxes)
  File "./imapdedup.py", line 208, in process
    mb = mb.decode('utf-7')
  File "/usr/lib/python2.7/encodings/utf_7.py", line 12, in decode
    return codecs.utf_7_decode(input, errors, True)
UnicodeDecodeError: 'utf7' codec can't decode bytes in position 122-124: partial character in shift sequence
```

I am running Python 2.7.15+ on Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-1040-aws x86_64)
