### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdf in position 11: ordinal not in range(128)

### ISSUE THREAD

**Issue by jpaechnatz** [quentinsf/IMAPdedup#17]
Traceback (most recent call last):
File "/usr/bin/imapdedup", line 271, in
main()
File "/usr/bin/imapdedup", line 216, in main
msg_id = get_message_id(mp, options.use_checksum, options.use_id_in_checksum)
File "/usr/bin/imapdedup", line 100, in get_message_id
md5.update(("Subject:" + parsed_message['Subject']).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdf in position 11: ordinal not in range(128)

**Comment by quentinsf** [comment]
Sorry I didn't respond to this at the time!
I think more recent updates will have fixed the problem, so I'm closing the issue, but do re-open it if needed!
Quentin
