### ISSUE TITLE
imaplib.error: command: SEARCH => got more than 10000 bytes

### ISSUE THREAD

**Issue by nigelhorne** [quentinsf/IMAPdedup#19]
How do I get rid of that error?

./imapdedup.py -s localhost Inbox -u xxxxx -n -m -c

**Comment by quentinsf** [comment]
Mmm.  I haven't seen that one - could you add the -v option, and give me a bit more information about just where it fails?

Q

**Comment by nigelhorne** [comment]
njh@nigelhorne:~/src/IMAPdedup$ ./imapdedup.py -s localhost Inbox -u xxxxx -n -m -c -v
Password: 

Warning: Unencrypted connection
There are 3668 messages in Inbox.
No message(s) currently marked as deleted in Inbox
Traceback (most recent call last):
  File "./imapdedup.py", line 278, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 275, in main
    process(options, mboxes)
  File "./imapdedup.py", line 194, in process
    msgnums = check_response(server.search(None, 'UNDELETED'))[0].split()
  File "/usr/lib/python2.7/imaplib.py", line 639, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/usr/lib/python2.7/imaplib.py", line 1087, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 913, in _command_complete
    raise self.error('command: %s => %s' % (name, val))
imaplib.error: command: SEARCH => got more than 10000 bytes

**Comment by quentinsf** [comment]
OK - this appears to be a problem with the underlying imap library, when the server returns a large number of messages.  I think it used to accept an arbitrary-length response from the server, but that can be dangerous, so recent Python versions (last 6 months or so) put a limit on it.

I don't think, though, that they've given an alternative way to get the list of messages in smaller chunks.  I'll explore.

I'm afraid all I can suggest until then is breaking the mailbox up into smaller ones, running the command, and then merging them back together.  This limit is per-mailbox, and you can specify multiple mailboxes on the command line, so you could do:

    ./imapdedup.py -s localhost ... Inbox1 Inbox2 Inbox3 ...

Q

**Comment by quentinsf** [comment]
Ah, here's an alternative which *might* solve the '10000 bytes' problem.
It's not an issue on my server, so I can't test it easily, but edit the script, and add an extra line after:

import imaplib

which says:

imaplib._MAXLINE = 200000

Does that solve the problem?
Quentin

**Comment by nigelhorne** [comment]
Yes, I think it does.  I say think because it does a lot before crashing with:

Traceback (most recent call last):
  File "./imapdedup.py", line 279, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 276, in main
    process(options, mboxes)
  File "./imapdedup.py", line 217, in process
    msg_id = get_message_id(mp, options.use_checksum, options.use_id_in_checksum)
  File "./imapdedup.py", line 108, in get_message_id
    md5.update(("Date:"    + str(parsed_message['Date'])).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 61: ordinal not in range(128)

**Comment by quentinsf** [comment]
Great - thanks - I'll put it in the code.

As for that other error, that's something confused in your mailbox.  By the looks of things, you have an é or similar in the Date of one of your messages!  If the script gave you enough information to work out which message is causing the problem, then I'd try moving it out of the mailbox temporarily, or move the messages around it if you're not sure of the exact one, and see if the rest will run.

Closing this issue for now.

**Comment by nigelhorne** [comment]
Yes, most likely it's failing to parse a message I have with this Date: header:

Date: Tue, 27 May 2003 07:53:35 +0200 (Paris, Madrid (heure d'été))

**Comment by nigelhorne** [comment]
Look at example A.5 in  RFC2822.  Although there are only ASCII characters in that time-zone example, the program should be able to parse headers of that type.

**Comment by quentinsf** [comment]
Ah - thanks - that's useful!  I hadn't thought about the timezone possibly having non-ASCII characters.
OK  - that's something to fix.

**Comment by quentinsf** [comment]
Actually, let me close this and open it as a new issue.
