### ISSUE TITLE
Message could be more helpful

### ISSUE THREAD

**Issue by nigelhorne** [quentinsf/IMAPdedup#20]
Message Inbox_13 is a duplicate of Inbox_11 and would be marked as deleted

Would it be possible to print the subject of those two messages please?

**Comment by quentinsf** [comment]
Nigel - 

Try the 'verbose' option (-v or --verbose). Does that do what you need?

All the best, 
Quentin

**Comment by nigelhorne** [comment]
Not really, since the -v option adds lot of other stuff e.g.

Checking Inbox message 894
f28a86bfd3bec8f17f783ac8024430a0
Checking Inbox message 895
5d57cae046d0f1f222a1c477329bb511
Checking Inbox message 896
e0a095e097af0ec8de18db3d251f73dd
Checking Inbox message 897
df5d39d9ae457f047808da1ccc81603e
Checking Inbox message 898
c26b1dbc00ec75651dc6eb51f0643f26
Checking Inbox message 899
af66d0bd034660f0dc66eeb639a5a2c8
Checking Inbox message 900
....

**Comment by quentinsf** [comment]
Mmm. OK - so ideally we'd have different levels of verbosity.

In the meantime, I suggest you edit the line number 228 and replace:

           if options.verbose:

with

           if True:

Q

**Comment by nigelhorne** [comment]
So I ran -v under script and the file is 2664 lines.  What am I looking for? The string Inbox_ isn't in the typescript file.

**Comment by quentinsf** [comment]
Look for 'is a duplicate of', like you had before. The Subject info should be just underneath it.

**Comment by nigelhorne** [comment]
Mmm. OK - so ideally we'd have different levels of verbosity.

In the meantime, I suggest you edit the line number 228 and replace:

       if options.verbose:

with

       if True:

**Comment by nigelhorne** [comment]
That helped tremendously, thanks, though it prints all headers not just the subject.

**Comment by quentinsf** [comment]
Yes, for more customisation than that, you'll need to edit the code!
 All the best, 
Q
