### ISSUE TITLE
Problems with timezone names including non-ASCII characters 

### ISSUE THREAD

**Issue by quentinsf** [quentinsf/IMAPdedup#21]
Originally raised in #19, @nigelhorne had a message with the date field:

Date: Tue, 27 May 2003 07:53:35 +0200 (Paris, Madrid (heure d'été))

This causes:

```
File "./imapdedup.py", line 108, in get_message_id
md5.update(("Date:" + str(parsed_message['Date'])).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 61: ordinal not in range(128)
```

**Comment by quentinsf** [comment]
Nigel - 

I've checked in an updated version which might solve this.

Quentin

**Comment by nigelhorne** [comment]
Sorry - I'm still getting:

  File "./imapdedup.py", line 279, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 276, in main
    process(options, mboxes)
  File "./imapdedup.py", line 217, in process
    msg_id = get_message_id(mp, options.use_checksum, options.use_id_in_checksum)
  File "./imapdedup.py", line 108, in get_message_id
    md5.update(("Date:"    + str(parsed_message['Date'])).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 61: ordinal not in range(128)

**Comment by quentinsf** [comment]
That's still the old version you're running...

Q

**Comment by nigelhorne** [comment]
I did a git pull first.  Do I need to do something else?

**Comment by quentinsf** [comment]
No - that should do it, but if you look at your traceback, line 108 doesn't look like line 108 in [the current version](https://github.com/quentinsf/IMAPdedup/blob/master/imapdedup.py) ...
