### ISSUE TITLE
Mailbox doesn't exist

### ISSUE THREAD

**Issue by brendabell** [quentinsf/IMAPdedup#26]
I get this exception when I try to execute on any mailbox where the name has embedded spaces:

Traceback (most recent call last):
  File "./imapdedup.py", line 218, in process
    msgs = check_response(server.select(mbox, options.dry_run))[0]
  File "./imapdedup.py", line 50, in check_response
    raise ImapDedupException("Got response: %s from server" % value)
**main**.ImapDedupException: Got response: [b"Mailbox doesn't exist: Apple"] from server

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./imapdedup.py", line 313, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 310, in main
    process(options, mboxes)
  File "./imapdedup.py", line 304, in process
    print >> sys.stderr, "Error:", e
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'

**Comment by nerijus** [comment]
Could you please show the full command line which you use? Could it be you don't put mailbox name in quotes?

**Comment by quentinsf** [comment]
Spaces should now be handled properly - you do need to put the name in quotes on the command line.
