### ISSUE TITLE
ValueError: invalid literal for int() with base 16

### ISSUE THREAD

**Issue by lehni** [quentinsf/IMAPdedup#28]
I am using the `-c` option on a mailbox and am getting this stack-trace. It look like it's there's a malformed email, with a word where the code expects a hex string:

```
  File "./imapdedup.py", line 313, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 310, in main
    process(options, mboxes)
  File "./imapdedup.py", line 249, in process
    msg_id = get_message_id(mp, options.use_checksum, options.use_id_in_checksum)
  File "./imapdedup.py", line 132, in get_message_id
    md5.update("Subject:" + utf8_header(parsed_message,'Subject'))
  File "./imapdedup.py", line 105, in utf8_header
    text, encoding = decode_header(parsed_message.get(name,''))[0]
  File "/usr/lib64/python2.6/email/header.py", line 93, in decode_header
    dec = email.quoprimime.header_decode(encoded)
  File "/usr/lib64/python2.6/email/quoprimime.py", line 336, in header_decode
    return re.sub(r'=\w{2}', _unquote_match, s)
  File "/usr/lib64/python2.6/re.py", line 151, in sub
    return _compile(pattern, 0).sub(repl, string, count)
  File "/usr/lib64/python2.6/email/quoprimime.py", line 324, in _unquote_match
    return unquote(s)
  File "/usr/lib64/python2.6/email/quoprimime.py", line 106, in unquote
    return chr(int(s[1:3], 16))
ValueError: invalid literal for int() with base 16: 'Th'
```

**Comment by quentinsf** [comment]
Hi Jürg,

Yes -- I'm not sure there's really a 'correct' fix for this.  You could try running with the '--verbose' option and it should tell you which message is causing the issue.  And you could use the '--checksum' option rather than depending on the Message-ID.

Does that help?

Quentin

**Comment by lehni** [comment]
Well maybe the code should just catch the exception? This one malformed email halts the whole program, which surely isn't ideal?

**Comment by quentinsf** [comment]
Mmm, sorry, yes - this is actually a corrupt 'Subject' line, not a corrupt Message-ID, so you probably were using the checksum option already.

The reason this is a bit tricky is that we just get back a 'ValueError' from the Python mail-processing library which says, in essence, 'This is corrupt data'.  If I catch and handle that, it might be too easy to miss more significant corruptions in other situations.

Still, here's a tweaked version - does that work for you?  I don't have an easy way to test it here.

[imapdedup.py.zip](https://github.com/quentinsf/IMAPdedup/files/328461/imapdedup.py.zip)
