### ISSUE TITLE
expected an indented block

### ISSUE THREAD

**Issue by Thomanji** [quentinsf/IMAPdedup#29]
Hi,

Any idea what the error below could be?

./imapdup.py -h
  File "./imapdup.py", line 310
    main(sys.argv[1:])
       ^
IndentationError: expected an indented block

**Comment by nerijus** [comment]
Most probably you copy/pasted and lost indentation. Python needs correct indentation.

**Comment by Thomanji** [comment]
Hi,
Yes you are absolutely correct, it works fine now.
Thank you for the superfast response and thank you for making this
Best wishes,
Thom

**Comment by nerijus** [comment]
Could you please close the issue?
