### ISSUE TITLE
Handling of names with umlauts

### ISSUE THREAD

**Issue by ghost** [quentinsf/IMAPdedup#30]
Hi, the script throws an exception if I try to use a directory with umlauts, like: Entw&APw-rfe or
Gel&APY-schte Elemente.

**Comment by ericschaetzlein** [comment]
Same for me:
`Traceback (most recent call last):
  File "imapdedup.py", line 324, in <module>
    main(sys.argv[1:])
  File "imapdedup.py", line 321, in main
    process(options, mboxes)
  File "imapdedup.py", line 208, in process
    mb = mb.decode('utf-7')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_7.py", line 12, in decode
    return codecs.utf_7_decode(input, errors, True)
UnicodeDecodeError: 'utf7' codec can't decode bytes in position 34-41: unterminated shift sequence
`

**Comment by quentinsf** [comment]
Mmm.  Yes, we should probably assume utf-8 now, or check for it in the appropriate imap header:
https://tools.ietf.org/html/rfc6855

I'll do it at some point unless somebody can provide me with a pull request first!

It's also probably time to switch to Python 3...

**Comment by quentinsf** [comment]
As a temporary fix, does it work if you change that line 208 to use utf-8 ?

**Comment by ericschaetzlein** [comment]
Hi Quentin,

thanks for the tipp, changing line 208 worked :)

All the best,
Eric

**Comment by quentinsf** [comment]
Closing this as I don't *think* it'll be an issue in the new version.
