### ISSUE TITLE
Issue with imapdedup

### ISSUE THREAD

**Issue by tayyabsaeed** [quentinsf/IMAPdedup#31]
Dear Sir,
We migrate lotus to zimbra, in migration we migrate some mailboxes 2 3 times because of network failure our large accounts stuck then we re-run migration wizard due to this we found duplicate emails in our zimbra mailboxes, We are using imapdedup but it fails to remove emails from those folders which contain spaces in their name, kindly give any solution if you have, we are very thankful to u.

ERROR is here:
Error: Got response: ['SELECT failed'] from server
Error: Got response: ['SELECT failed'] from server
Error: Got response: ['SELECT failed'] from server
Traceback (most recent call last):
File "imapdedup.py", line 310, in
main(sys.argv[1:])
File "imapdedup.py", line 307, in main
process(options, mboxes)
File "imapdedup.py", line 215, in process
msgs = check_response(server.select(mbox, options.dry_run))[0]
File "/usr/lib64/python2.7/imaplib.py", line 661, in select
typ, dat = self._simple_command(name, mailbox)
File "/usr/lib64/python2.7/imaplib.py", line 1082, in _simple_command
return self._command_complete(name, self._command(name, *args))
File "/usr/lib64/python2.7/imaplib.py", line 917, in _command_complete
raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: SELECT command error: BAD ['parse error: zero-length content']

**Comment by quentinsf** [comment]
I'm sorry - I've only just seen this, and I'm probably much too late to be of any help, but if you have mailbox names with spaces in them, you need to put them in quotes.

I'll add that to the documentation.

All the best, 
Quentin

**Comment by tayyabsaeed** [comment]
Thanks a lot for your email.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Quentin Stafford-Fraser <notifications@github.com> Date: 16/03/2017  04:28  (GMT+05:00) To: quentinsf/IMAPdedup <IMAPdedup@noreply.github.com> Cc: tayyabsaeed <tayyab.saeed@nds.com.pk>, Author <author@noreply.github.com> Subject: Re: [quentinsf/IMAPdedup] Issue with imapdedup (#31) 
I'm sorry - I've only just seen this, and I'm probably much too late to be of any help, but if you have mailbox names with spaces in them, you need to put them in quotes.
I'll add that to the documentation.
All the best,

Quentin

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/quentinsf/IMAPdedup","title":"quentinsf/IMAPdedup","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/quentinsf/IMAPdedup"}},"updates":{"snippets":[{"icon":"PERSON","message":"@quentinsf in #31: I'm sorry - I've only just seen this, and I'm probably much too late to be of any help, but if you have mailbox names with spaces in them, you need to put them in quotes.\r\n\r\nI'll add that to the documentation.\r\n\r\nAll the best, \r\nQuentin\r\n"}],"action":{"name":"View Issue","url":"https://github.com/quentinsf/IMAPdedup/issues/31#issuecomment-286911685"}}}
