### ISSUE TITLE
pull password from env?

### ISSUE THREAD

**Issue by jvanasco** [quentinsf/IMAPdedup#34]
Hi.  I wanted to suggest a slight change -- grabbing the password off the environment.

This avoids constantly having to type it into the commandline or writing a wrapper script...

```
    + import os
    ...

     if not options.password and not options.process:
    -    options.password = getpass.getpass()
    +    options.password = os.getenv('IMAPdedup_pass') or getpass.getpass()
```

so then you just invoke it as:

    export IMAPdedup_pass=sekrit
    ./imapdedup.py -s foo -u bar -x "INBOX"
    ./imapdedup.py -s foo -u bar -x "INBOX.2"
    ./imapdedup.py -s foo -u bar -x "INBOX.3"

and you're not prompted for the password.

**Comment by quentinsf** [comment]
Thanks Jonathan - I like that - it's now in there, though I went for a more traditional all-upper-case variable name!

IMAPDEDUP_PASSWORD

Sorry I took so long to get around to it :-)
