### ISSUE TITLE
request

### ISSUE THREAD

**Issue by donb123github** [quentinsf/IMAPdedup#35]
How about making it recursively scan all folders in the mailbox looking for dupes?

**Comment by quentinsf** [comment]
That's an interesting idea, but the problem would be the ordering.  

At the moment, if you specify multiple folders for a single scan, the procedure is well-defined:  the folders are examined in the order specified, and the first occurrence of a message is left, while later duplicates are marked for deletion.

I'm not sure there's a natural ordering to decide which ones to keep if the folder list is generated automatically.  Alphabetic?  But then ones in an Archive would be kept in preference to ones in an Inbox...

I think this rules the option out, so am closing the ticket, but do re-open it if I've missed something and there's a good solution.

Best,
Quentin
