### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by alexisskeates** [quentinsf/IMAPdedup#36]
If I use the config file and specific multiple folders is each folder processed individually or or does the script compare between folders?

I want to be able to run this through our public folder set, but only want it to remove duplicate emails within the same folder not duplicate emails across folders.

**Comment by quentinsf** [comment]
Hi there - 

I had to go and look at the source to remind myself, and then found that this is actually in the documentation :-)

> You can specify multiple folders to work on, and it work through them in order and will delete, in the later folders, duplicates of messages that it has found either in those folders or in earlier ones.

So it probably doesn't do what you want for your particular case - you would need to run the script multiple times, once per mailbox.

Hope that helps,
All the best, 
Quentin
