### ISSUE TITLE
Mailbox doesn't exist

### ISSUE THREAD

**Issue by SimonSchmitz** [quentinsf/IMAPdedup#38]
./imapdedup.py -s ***.***.** -u *** -w ******* -x -l
Drafts
Sent
Sent.2011
Sent.2014
Sent.2012
Sent.2013
Sent.2016
Sent.2015
Sent.2017
Junk
Trash
INBOX.2011
INBOX.2012
INBOX.2013
INBOX.2014
INBOX.2015
INBOX.2016
Archiv
INBOX

./imapdedup.py -s ***.***.** -u *** -w ****** -x -n INBOX
Error: Got response: ["Mailbox doesn't exist: m (0.000 + 0.000 secs)."] from server

./imapdedup.py -s ***.***.** -u *** -w ****** -x -n "INBOX"
Error: Got response: ["Mailbox doesn't exist: m (0.000 + 0.000 secs)."] from server

./imapdedup.py -s ***.***.** -u *** -w ****** -x -n 'INBOX'
Error: Got response: ["Mailbox doesn't exist: m (0.000 + 0.000 secs)."] from server

**Comment by ngortheone** [comment]
I got this too when I had nested folders with no messages in intermediate folder
