### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by iranzo** [quentinsf/IMAPdedup#46]
Hi,
When running imapdedup with python3 (3.7.5), I get:

Traceback (most recent call last):
  File "/home/iranzo/.bin/imapdedup.py", line 324, in <module>
    main(sys.argv[1:])
  File "/home/iranzo/.bin/imapdedup.py", line 321, in main
    process(options, mboxes)
  File "/home/iranzo/.bin/imapdedup.py", line 246, in process
    message_ids = ','.join(msgnums_in_chunk)
TypeError: sequence item 0: expected str instance, bytes found

Same binary executed with python2 works fine, seems UTF conversion that gives bytes instead of regular str

**Comment by quentinsf** [comment]
Hi Pablo - 

Yes, it's high time I switched this over to being purely Python 3.  

I haven't had a chance to do anything with IMAPdedup for some time, so it's been stuck in the old world!  In addition, the handling of unicode depends to some degree on the configuration of the mail server, I believe.


As a quick fix, if the msgnums value in line 238 is being returned as bytes, you might try changing the '.split()' on the end of that line to '.decode().split()'...

**Comment by quentinsf** [comment]
Closing this as I'm in the process of migrating IMAPdedup to Python3
