### ISSUE TITLE
Not an issue at all!!

### ISSUE THREAD

**Issue by tonoriesco** [quentinsf/IMAPdedup#53]
Just I wanted to say thank you to all the team and specially to Quentin,

I had more than 5000 duplicates in years and years of moving imap folders between servers and today you saved my life!

Sorry about filling an issue but I didn't find your email.

Cheers.

Tono.

**Comment by quentinsf** [comment]
Thanks, Tono!   It's very nice to get an issue that isn't an issue!   I'm glad you found it helpful!

All the best,
Quentin
