### ISSUE TITLE
Support STARTTLS

### ISSUE THREAD

**Issue by devurandom** [quentinsf/IMAPdedup#6]
Some servers support STARTTLS, which Python supports since v3.2: http://docs.python.org/dev/library/imaplib.html#imaplib.IMAP4.starttls

**Comment by vchrizz** [comment]
closed without comment?!
please reopen or implement tls, imaplib is able to use starttls.
i would need this to dedup mails on an exchange server, please give some update about it, thanks! :)

**Comment by nerijus** [comment]
No, it was closed with merging #7, so STARTTLS is used by default now.

**Comment by vchrizz** [comment]
Oh right, sorry, didn't see that before.
Strange, I can't properly connect to my exchange server. Trying to debug why, I noticed the script hangs at the point of (or after?) starttls. I tried to print server capabilities and STARTTLS is mentioned. But still the script hangs at this check..?

**Comment by quentinsf** [comment]
Hi Cristoph - sorry, I don't have access to an Exchange server, so can't test this.

Perhaps someone else can say whether or not it works for them...

All the best, 
Quentin

**Comment by vchrizz** [comment]
Not sure what exactly was wrong before, the scrit just couldn't connect and it was hanging without doing anything. I was just trying to debug that again and now when I would like to show the exact problem, there is none. Now it works...?!
So I can confirm support of starttls and exchange.
`-l` shows all my folders.
Many thanks!
