### ISSUE TITLE
Using sed to quote each line for processing with xargs

### ISSUE THREAD

**Issue by sschwetz** [quentinsf/IMAPdedup#75]
If you are using an operating system with xargs you can use sed to automatically quote each line of your input by piping it through sed. For example:

```
cat folders.txt | sed 's/^\(.*\)$/"\1"/' | xargs ./imapdedup.py -s imap.server -w supersecretpasword -u imapusername -x -v -S
```

I thought that you might like to add this to examples in your readme.md

Thanks for writing this, it is a godsend :)

**Comment by quentinsf** [comment]
Thanks Stephen!  I've updated the README.

All the best, 
Quentin
