### ISSUE TITLE
IMAPdedup problems with non-ASCII mailbox names

### ISSUE THREAD

**Issue by ericschaetzlein** [quentinsf/IMAPdedup#79]
I have a mailbox folder with the German name "Entwürfe".

When I use the list (-l) option, IMAPdedup returns "Entw&APw-rfe".
When I use the list output as input for the next run (as suggested if you want to search ALL mailboxes), IMAPdedup quits with an error
Error: Got response: [b'unknown folder'] from server

It seems logical to me that the output mailbox name should be the same used as input mailbox name.

But then again, if I use "Entwürfe" as input mailbox name, IMAPdedup quits with an error
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 4: ordinal not in range(128)

So finally it seems that IMAPdedup cannot cope with non-ascii folders at all.

**Comment by ericschaetzlein** [comment]
I am very sorry, today I can't reproduce the error "Got response: [b'unknown folder'] from server" anymore.
It works several times in a row like a charme.

**Comment by quentinsf** [comment]
Hi Eric - well, I'm glad it works for you now!  I was going to take a look at this... I wondered whether you might have been using Python 2 instead of Python 3, perhaps?

**Comment by ericschaetzlein** [comment]
Hi Quentin,

thanks for replying to me. Meanwhile, I came to the conclusion that, while editing the folder list to make sure the "bad" folders are at the bottom, I must have made a typo.
Simple as that :-)

Otherwise, the tool works as charm :-)

All the best,
Eric
