### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\D'

### ISSUE THREAD

**Issue by markk** [quentinsf/IMAPdedup#81]
In this line:

https://github.com/quentinsf/IMAPdedup/blob/b232a13bf923292dccb0dd22a78b74e20950daf3/imapdedup.py#L348

`(\Deleted)` should be `(\\Deleted)`, or alternatively the whole comment tagged as a raw string (r""" ... """). This triggers a SyntaxWarning since Python 3.12.

https://docs.python.org/3/whatsnew/3.12.html#other-language-changes

**Comment by quentinsf** [comment]
Thanks Mark - sorry I didn't respond, but this is fixed in recent commits!
All the best, Quentin
